### ISSUE TITLE
Grün trotz falscher IP

### ISSUE THREAD

**Issue by DEV2DEV-DE** [BenAhrdt/ioBroker.paperless-ngx#18]
Jagt man den Adapter auf eine falsche IP, wird er trotzdem grün, produziert aber (logischerweise) fleißig Fehlermeldungen im Log.
Das gleiche passiert übrigens auch, wenn man die korrekte IP, aber einen falschen Benutzernamen verwendet.

**Comment by BenAhrdt** [comment]
> Jagt man den Adapter auf eine falsche IP, wird er trotzdem grün, produziert aber (logischerweise) fleißig Fehlermeldungen im Log. Das gleiche passiert übrigens auch, wenn man die korrekte IP, aber einen falschen Benutzernamen verwendet.

Auch hier werde ich wohl erst frühestens nächste Woche dazu kommen, mir das ansehen zu können.

**Comment by BenAhrdt** [comment]
sollte mit 0.1.2 behoben sein.
