### ISSUE TITLE
Fehler beim ersten Start

### ISSUE THREAD

**Issue by DEV2DEV-DE** [BenAhrdt/ioBroker.paperless-ngx#19]
Unmittelbar nach der Installation einer Instanz werden die Parameter abgefragt.
Irgendwie versucht die Instanz sich aber bereits ohne Daten zu verbinden, was natürlich mit entsprechenden Fehlern quittiert wird.

```
paperless-ngx.0 | 2024-10-23 22:37:33.553 | error | error at readUsers:  TypeError: Invalid URL
paperless-ngx.0 | 2024-10-23 22:37:33.543 | error | error at readTags:  TypeError: Invalid URL
```

**Comment by BenAhrdt** [comment]
> Unmittelbar nach der Installation einer Instanz werden die Parameter abgefragt. Irgendwie versucht die Instanz sich aber bereits ohne Daten zu verbinden, was natürlich mit entsprechenden Fehlern quittiert wird.
> 
> ```
> paperless-ngx.0 | 2024-10-23 22:37:33.553 | error | error at readUsers:  TypeError: Invalid URL
> paperless-ngx.0 | 2024-10-23 22:37:33.543 | error | error at readTags:  TypeError: Invalid URL
> ```

OK, das hatte ich noch nicht behandelt. Werde vermutlich frühestens nächste Woche dazu kommen mir das anzusehen.

**Comment by BenAhrdt** [comment]
sollte mit 0.1.2 behoben sein.
