### ISSUE TITLE
Feature-Request: Korrespondenten

### ISSUE THREAD

**Issue by DEV2DEV-DE** [BenAhrdt/ioBroker.paperless-ngx#20]
Toll wäre, wenn man neben den Tags, Dokumententypen und Benutzern auch die Korrespondenten ermitteln könnte.
Ich könnte damit erkennen, ob Dokumente über den Scanner oder per Mail angekommen sind.
Was über den Scanner kommt, wurde ja bewusst angeschubst - da kann ich mir meine Benachrichtigung sparen ;-)

**Comment by BenAhrdt** [comment]
> Toll wäre, wenn man neben den Tags, Dokumententypen und Benutzern auch die Korrespondenten ermitteln könnte. Ich könnte damit erkennen, ob Dokumente über den Scanner oder per Mail angekommen sind. Was über den Scanner kommt, wurde ja bewusst angeschubst - da kann ich mir meine Benachrichtigung sparen ;-)

Ich habe es in der V 0.1.1 implementiert.
Bitte testen. Danke

**Comment by DEV2DEV-DE** [comment]
Scheint auf den ersten Blick zu funktionieren wie erwartet. Sollte was sein, melde ich mich.
Danke für die prompte Bedienung ;-)
